### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Endless-AI-Invade#2]
Do you have any designs planed? If not, I can suggest stuff.

<details><summary>Idea</summary>
<p>

Melbat:
![melbat](https://github.com/OcelotWalrus/Endless-AI-Invade/assets/125756761/428dc781-6efb-47de-9c51-e86dafa196c3)
A civilian warship. (GitHub seems to have cropped it, but it shows the full thing if you click on it)

Velbat:
![velbat](https://github.com/OcelotWalrus/Endless-AI-Invade/assets/125756761/07da5c40-eedf-4dc7-bd63-92570217f007)
A gunboat type military warship.

</p>
</details>

**Comment by OcelotWalrus** [comment]
No I don't, but I prefer searching for ideas on my own but thanks! I did not planned anything for now on.

**Comment by lumbar527** [comment]
It's fine; I just see you doing stuff and want to contribute. So I dug up an old ship image and some names and posted them. Maybe I'll make my own plugin that they were originally planned for.

I'm uploading my plugin to GitHub [here](https://github.com/lumbar527/ES-Galactic-Exploration) if you want to check it out.

**Comment by OcelotWalrus** [comment]
I do not say they're bad or that I want to work on this by myself, I just say that I need sometime to figure out the basic ideas of this plugin. I will inform you when I'll be done.

**Comment by OcelotWalrus** [comment]
I just want to have a clear idea of what this plugin will be.

**Comment by lumbar527** [comment]
OK, I'll wait until it's ready.
